---
all: 
    hosts:
        PXEServer:
          ansible_host: 127.0.0.1
          ansible_port: 2200
          ansible_private_key_file: /root/OTUS/Kazay/PXE/.vagrant/machines/pxeserver/virtualbox/private_key
          